# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=20, verbose_name='城市名称')),
                ('CityDescribe', models.TextField(verbose_name='城市描述')),
                ('AddTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='CourseOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.CharField(max_length=50, verbose_name='组织名称')),
                ('OrganizationDescribe', models.TextField(verbose_name='组织描述')),
                ('ClickNumber', models.IntegerField(default=0, verbose_name='点击数')),
                ('FavoriteNumber', models.IntegerField(default=0, verbose_name='收藏数')),
                ('OrganizationImage', models.ImageField(upload_to='org/%Y/%m', verbose_name='组织封面')),
                ('Address', models.CharField(max_length=200, verbose_name='组织地址')),
                ('AddTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('StudentNumber', models.IntegerField(default=0, verbose_name='学习人数')),
                ('CourseNumber', models.IntegerField(default=0, verbose_name='课程数')),
                ('Caterory', models.CharField(choices=[('pxjg', '培训机构'), ('gr', '个人'), ('gx', '高校')], default='pxjg', max_length=20, verbose_name='机构类别')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '课程机构',
                'verbose_name_plural': '课程机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=50, verbose_name='教师名称')),
                ('WorkLife', models.IntegerField(default=0, verbose_name='工作年限')),
                ('WorkCompany', models.CharField(max_length=50, verbose_name='就职公司')),
                ('WorkPosition', models.CharField(max_length=50, verbose_name='职位')),
                ('Point', models.CharField(max_length=50, verbose_name='教学特点')),
                ('ClickNumber', models.IntegerField(default=0, verbose_name='点击数')),
                ('FavoriteNumber', models.IntegerField(default=0, verbose_name='收藏数')),
                ('AddTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('TeacherImage', models.ImageField(blank=True, null=True, upload_to='teacher/%Y/%m', verbose_name='教师头像')),
                ('BelongOrganization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrganization', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
    ]
