# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-17 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Characteristic',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='教学特点'),
        ),
    ]
