# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Describe', models.CharField(max_length=500, verbose_name='课程简介')),
                ('CourseName', models.CharField(max_length=100, verbose_name='课程名称')),
                ('Detail', models.TextField(verbose_name='课程详情')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=10, verbose_name='课程难度')),
                ('LearnTime', models.IntegerField(default=0, verbose_name='学习时长')),
                ('CourseType', models.CharField(max_length=30, verbose_name='课程类型')),
                ('CoursePicture', models.ImageField(max_length=500, upload_to='courses/%Y/%m', verbose_name='课程封面')),
                ('Students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('FavouriteNumber', models.IntegerField(default=0, verbose_name='喜欢人数')),
                ('ClikeNumber', models.IntegerField(default=0, verbose_name='点击人数')),
                ('AddTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('Tag', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='所属机构')),
                ('Organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrganization', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='名称')),
                ('DownLoad', models.CharField(max_length=100, verbose_name='下载')),
                ('AddTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LessonName', models.CharField(blank=True, default='未命名', max_length=100, null=True, verbose_name='章节名称')),
                ('AddTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideoName', models.CharField(max_length=100, verbose_name='视频名称')),
                ('AddTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('LessonName', models.ForeignKey(default='未命名', on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节名称')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
    ]
