# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='LearnTest',
            field=models.IntegerField(default=0, verbose_name='测试'),
        ),
    ]
