# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-04 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_learntest'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='VideoUrl',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='播放路径'),
        ),
    ]
