# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_learntime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='DownLoad',
            field=models.FileField(upload_to='course/resource/%Y/%m/%d', verbose_name='下载'),
        ),
    ]
