# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-04 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('courses', '0006_auto_20180204_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='课程老师'),
        ),
        migrations.AddField(
            model_name='course',
            name='TeacherTellYou',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='老师告诉你的'),
        ),
        migrations.AddField(
            model_name='course',
            name='YouNeedKonw',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='课程须知'),
        ),
    ]
