# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180204_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AddField(
            model_name='course',
            name='Display',
            field=models.BooleanField(default=False, verbose_name='展示与否'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Tag',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='标签'),
        ),
    ]
