# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171113_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日日期'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(default='Banner/default.png', upload_to='Banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
