# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171114_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='send_type',
            field=models.CharField(choices=[('reguster', '注册'), ('forget', '忘记密码')], max_length=20, verbose_name='发送类型'),
        ),
    ]
