# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171211_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(default='Banner/default.png', upload_to='static/Pic/Banner/%Y/%m/%d', verbose_name='轮播图'),
        ),
    ]
